### ISSUE TITLE
SUSE 11SP3 doesn't support __BYTE_ORDER__/__ORDER_BIG_ENDIAN__

### ISSUE THREAD

**Issue by colorjiang** [barbieri/barbieri-playground#1]
SUSE 11SP3 doesn't support __BYTE_ORDER__/__ORDER_BIG_ENDIAN__.

maybe __BYTE_ORDER/__BIG_ENDIAN is better, which is defined in SUSE 11SP3.
reference: https://sourceforge.net/p/predef/wiki/Endianness/

**Comment by barbieri** [comment]
that wiki also mentions what I use `__ORDER_BIG_ENDIAN`... see 1f94859aaeca856180a611e53d7ff219d3098a3c if it helps
