### ISSUE TITLE
wifi-disconnect-low-signal does not work properly

### ISSUE THREAD

**Issue by verifyurhuman** [barbieri/barbieri-playground#24]
Hello barbieri, I followed your guide but seems it doesn't work as expected. My phone still sticks to it even if the log shows it's disconnected.

**Here's my config:**
```
	option signal_connect '-60'
	option signal_stay '-70'
	option signal_strikes '2'
	option signal_poll_time '3'
```

**Checking system log:**

1. starting the script with my phone in strong signal

```
Wed Aug 16 17:29:24 2023 user.debug wifi-disconnect-low-signal: radio0: phy0-ap0 {signal_connect=-60dBm, signal_stay=-70dBm, poll_time=3s, strikes=2, drop_reason=3}
Wed Aug 16 17:29:24 2023 user.debug wifi-disconnect-low-signal: radio1: disabled by config file
Wed Aug 16 17:29:24 2023 user.debug wifi-disconnect-low-signal: found 1 enabled WiFi devices
Wed Aug 16 17:29:24 2023 user.debug wifi-disconnect-low-signal: phy0-ap0: FC:BE:7B:1E:68:0D signal=-52dBm snr=46dBm strikes=0 (threshold: signal_connect=-60 strikes=0): good signal
Wed Aug 16 17:29:24 2023 user.debug wifi-disconnect-low-signal: phy0-ap0: signal poll: 1 STAs, 0 disconnected
Wed Aug 16 17:29:27 2023 user.debug wifi-disconnect-low-signal: phy0-ap0: FC:BE:7B:1E:68:0D signal=-52dBm snr=46dBm strikes=0 (threshold: signal_stay=-70 strikes=2): good signal
Wed Aug 16 17:29:27 2023 user.debug wifi-disconnect-low-signal: phy0-ap0: signal poll: 1 STAs, 0 disconnected
```

2. moving away my phone

```
Wed Aug 16 17:32:04 2023 user.debug wifi-disconnect-low-signal: phy0-ap0: FC:BE:7B:1E:68:0D signal=-67dBm snr=31dBm strikes=0 (threshold: signal_stay=-70 strikes=2): good signal
Wed Aug 16 17:32:04 2023 user.debug wifi-disconnect-low-signal: phy0-ap0: signal poll: 1 STAs, 0 disconnected
Wed Aug 16 17:32:07 2023 user.debug wifi-disconnect-low-signal: phy0-ap0: FC:BE:7B:1E:68:0D signal=-76dBm snr=22dBm strikes=1 (threshold: signal_stay=-70 strikes=2): bad signal
Wed Aug 16 17:32:07 2023 user.debug wifi-disconnect-low-signal: phy0-ap0: signal poll: 1 STAs, 0 disconnected
Wed Aug 16 17:32:10 2023 user.debug wifi-disconnect-low-signal: phy0-ap0: FC:BE:7B:1E:68:0D signal=-76dBm snr=22dBm strikes=2 (threshold: signal_stay=-70 strikes=2): should disconnect
Wed Aug 16 17:32:10 2023 user.info wifi-disconnect-low-signal: phy0-ap0: disconnected FC:BE:7B:1E:68:0D {signal=-76dBm, noise=-98dBm, snr=22dBm, strikes=2, is_new=false}
Wed Aug 16 17:32:10 2023 user.debug wifi-disconnect-low-signal: phy0-ap0: signal poll: 1 STAs, 1 disconnected
Wed Aug 16 17:32:13 2023 user.debug wifi-disconnect-low-signal: phy0-ap0: signal poll: 0 STAs, 0 disconnected
Wed Aug 16 17:32:16 2023 user.debug wifi-disconnect-low-signal: phy0-ap0: signal poll: 0 STAs, 0 disconnected
```

3. but only to find my phone still connected!

4. then I made my phone stay in low signal area

```
Wed Aug 16 17:33:10 2023 user.debug wifi-disconnect-low-signal: phy0-ap0: signal poll: 0 STAs, 0 disconnected
Wed Aug 16 17:33:13 2023 user.debug wifi-disconnect-low-signal: phy0-ap0: signal poll: 0 STAs, 0 disconnected
Wed Aug 16 17:33:13 2023 user.debug wifi-disconnect-low-signal: phy0-ap0: forget FC:BE:7B:1E:68:0D
Wed Aug 16 17:33:16 2023 user.debug wifi-disconnect-low-signal: phy0-ap0: FC:BE:7B:1E:68:0D signal=-71dBm snr=28dBm strikes=1 (threshold: signal_connect=-60 strikes=0): should disconnect
Wed Aug 16 17:33:16 2023 user.info wifi-disconnect-low-signal: phy0-ap0: disconnected FC:BE:7B:1E:68:0D {signal=-71dBm, noise=-99dBm, snr=28dBm, strikes=1, is_new=true}
Wed Aug 16 17:33:16 2023 user.debug wifi-disconnect-low-signal: phy0-ap0: signal poll: 1 STAs, 1 disconnected
Wed Aug 16 17:33:19 2023 user.debug wifi-disconnect-low-signal: phy0-ap0: signal poll: 0 STAs, 0 disconnected
Wed Aug 16 17:33:22 2023 user.debug wifi-disconnect-low-signal: phy0-ap0: signal poll: 0 STAs, 0 disconnected
```

5. finally I found my phone still connected to it.

**Additional Info:**
Router: [tp-link tl-wdr6500](https://openwrt.org/toh/hwdata/tp-link/tp-link_tl-wdr6500_v2)
Version: [openwrt official nightly build](https://firmware-selector.openwrt.org/?version=SNAPSHOT&target=ath79%2Fgeneric&id=tplink_tl-wdr6500-v2)
Working Mode: [dumb ap](https://openwrt.org/docs/guide-user/network/wifi/dumbap)

Thank you in advance!

**Comment by barbieri** [comment]
note that since a while we're using `wnm_disassoc_imminent` to disconnect, please check if your AP/hw supports that.

**Comment by barbieri** [comment]
@Request-timed-out could you comment on the outcome? Was it working? Do you know if your HW supports `wnm_disassoc_imminent`?

**Comment by verifyurhuman** [comment]
@barbieri sadly not. I just gave up. 

At first I wanted to configure 802.11r to set up wifi roaming only to find some of my devices not support it, so I turned to using sth that auto disconnects when low rssi, then I found here. But it didn't work as I followed the guide. Then I opened this issue. I was about to dig into the problem with your advice when I found my vacation nearly run out, time to go to college, so I gave up.

My house is not big, with one floor but many thick walls, I have to use two wifis to keep the signal strong enough. Now I switch between them manually, just like I used to.

**Comment by barbieri** [comment]
ok, thanks for sharing. I'm not using it myself, 3 years ago I moved from various hardware running openwrt to UniFi AP. Unfortunately for openwrt there are many hardware with various support, so my guess would be `wnm_disassoc_imminent` is not supported by yours.

**Comment by verifyurhuman** [comment]
@barbier if you don't mind writing more, how do i check if it is supported? are there a list or table etc.? i googled and asked chatgpt but very little info i can get from.

**Comment by barbieri** [comment]
Try to revert https://github.com/barbieri/barbieri-playground/commit/b1326919d2eb768c173203bdc18fe4627487816e and see if going back to del_client will solve it.

This effectively kicks the client, not just a notification "will disconnect you, go somewhere else"

Actually, I'm thinking we could do the del_client after a timeout...
