### ISSUE TITLE
efl-win64-install.py not work

### ISSUE THREAD

**Issue by bigov** [barbieri/barbieri-playground#3]
Archlinux is no have this toolchain. MinGW moved in the AUR:

```
$ python3 ./efl-win64-install.py 
missing toolchain (x86_64-w64-mingw32-gcc) in $PATH

```

**Comment by barbieri** [comment]
hi @bigov , I'm not using this script anymore and I don't have time to maintain it.

if you send a PR, I can apply with your fixes, but that's basically it :-(

**Comment by bigov** [comment]
Hi, @barbieri,  I don't have the necessary experience to do it quickly enough. Sorry, this is not in my plans.
