### ISSUE TITLE
wifi disconnect config interpretation

### ISSUE THREAD

**Issue by cybermaus** [barbieri/barbieri-playground#4]
Hello. 

I was playing with your wifi-disconnect, and I while I got it working, I do have to report some suggestions. Please note that this does not lessen my appreciation for writing and publishing the tool.
ALso, I am always open to the suggestion I am simply using it wrong, in which case my appologies.

I have 4 items, listed below

1) It is unable to read the wifi-iface section if those sections are not named.
My Luci generates, and also the OpenWRT wiki does not show allowance for labels for the wifi-iface section headers.
Your example does show them. It turns out if these labels are not present, your script is not able to interpret the values:

So this works
```
config wifi-iface 'default_radio0'
	option device 'radio0'
	option mode 'ap'
	option network 'lan'
	option ssid 'my-wifi'
	option key 'my-passwd'
	option encryption 'psk2+ccmp'
	option signal_snr_connect '25'
	option signal_snr_stay '20'
	option signal_strikes '3'
	option signal_poll_time '5'
	option signal_drop_reason '3'
```
But this is how a normal generated section looks, and it does not work with your script:
(to be quite honest, I am not even sure what the 'default_radio0' in your example above is supposed to do, as it is not described in OpenWRT WiKi
```
config wifi-iface
	option device 'radio0'
	option mode 'ap'
	option network 'lan'
	option ssid 'my-wifi'
	option key 'my-passwd'
	option encryption 'psk2+ccmp'
	option signal_snr_connect '25'
	option signal_snr_stay '20'
	option signal_strikes '3'
	option signal_poll_time '5'
	option signal_drop_reason '3'
```

2) When it starts running, it seems that even though "strikes=3" is set, it at first uses value "strikes=0"

```
root@W115_Spare:/tmp# lua wifi-disconnect-low-signal.lua -v -v --stderr
wifi-disconnect-low-signal: radio0: wlan0 {signal_connect=-20dBm, signal_stay=-30dBm, poll_time=5s, strikes=3, drop_reason=3}
wifi-disconnect-low-signal: radio0: wlan0-1 {signal_connect=-20dBm, signal_stay=-30dBm, poll_time=5s, **_strikes=3_**, drop_reason=3}
wifi-disconnect-low-signal: found 2 enabled WiFi devices
wifi-disconnect-low-signal: wlan0: 00:27:22:76:1A:47 signal=-42dBm snr=53dBm strikes=1 (threshold: signal_connect=-20 **_strikes=0_**): should disconnect
wifi-disconnect-low-signal: wlan0: disconnected 00:27:22:76:1A:47 {signal=-42dBm, noise=-95dBm, snr=53dBm, strikes=1, is_new=true}
wifi-disconnect-low-signal: wlan0: signal poll: 1 STAs, 1 disconnected
wifi-disconnect-low-signal: wlan0-1: no associated STAs
wifi-disconnect-low-signal: wlan0: signal poll: 0 STAs, 0 disconnected
```
```
root@W115_Spare:/tmp# lua wifi-disconnect-low-signal.lua -v -v --stderr
wifi-disconnect-low-signal: radio0: wlan0 {signal_connect=-128dBm, signal_stay=-128dBm, poll_time=3s, **_strikes=3_**, drop_reason=3}
wifi-disconnect-low-signal: radio0: wlan0-1 {signal_connect=-128dBm, signal_stay=-128dBm, poll_time=3s, **_strikes=3_**, drop_reason=3}
wifi-disconnect-low-signal: found 2 enabled WiFi devices
wifi-disconnect-low-signal: wlan0: 00:27:22:76:1A:47 signal=-42dBm snr=53dBm strikes=0 (threshold: signal_connect=-128 **_strikes=0_**): good signal
wifi-disconnect-low-signal: wlan0: signal poll: 1 STAs, 0 disconnected
wifi-disconnect-low-signal: wlan0-1: no associated STAs
wifi-disconnect-low-signal: wlan0: 00:27:22:76:1A:47 signal=-41dBm snr=54dBm strikes=0 (threshold: signal_stay=-128 **_strikes=3_**): good signal
wifi-disconnect-low-signal: wlan0: signal poll: 1 STAs, 0 disconnected
wifi-disconnect-low-signal: wlan0-1: no associated STAs
```
So to restate, in the latter case, it first reports finding config for 3 allowed strikes (correct) then at least once acts on a 0 allowed strikes rule (incorrect) then later again reports 3 allowed strikes (correct again, but now the client is already disconnected). So something is 'up' with the strike counter.

3) You should probably not log or even interpret non-AP wifi-iface sections
Most of my AP have only 3 AP ( 3-VLAN) but a few have 3-STA-WDS and 3-AP-WDS. Because they act as (low traffic) 3-VLAN repeater. Yes, ugly, I know. It makes logging rather verbose with all 6 sections logging, and I worry it also takes more CPU then needed.

4) You should probably not log or even interpret any wifi-iface sections where no connect_* options are given. My 3-SSID on 3-VLAN solutions has one isolated VLAN for Internet of Things, one for Management, one for Guests. I really only want the Guests to be disconnected or ruled.

Of course I can leave the defaults of -128dB, it works. But it makes logging rather verbose with all 6 sections logging, and I worry it also takes more CPU then needed.

Anyway. Many thanks.

**Comment by cybermaus** [comment]
Playing more with it, I realise item 2) above is intentional. It is how you implemented "new" connections.
So ignore 2). Also ignore 3), I think I may want the option to also disconnect AP from STA.

1) and 4) remains something to be considered please.
The first to make more compatible with generated /etc/config/wireless files
And the last to save on CPU. Not interpreting interfaces that do not have parameters set.

Thanks

**Comment by barbieri** [comment]
indeed, the new connection is intentional. As for the "verbose logging", the idea was to make it easier to debug... I'll check if I can reduce the verbosity a bit.

As for 1, I did use what my LEDE (at the moment that I wrote, it was using the lede project) and it had that... I can adapt to something different, sure.

In 4, I'll check my usages (I don't recall, it's been a while) and see... but it should be doable to ignore if there is no configuration set. BUT, there is no way "to not parse", since they are in the same file, I can parse and throw away. What I'll investigate is if my script consumes resources because of that, it shouldn't... this happens on startup, only once, and shouldn't bring significant overhead.

**Comment by cybermaus** [comment]
If it does not matter for CPU (if you have to parse the entire set of interfaces anyway) then the item 4)is not too important. After all, I only am looking at it while debugging, and probably forgetting about it later. 

At this moment, it is working. In fact, what I did to ease roll-out to all my camp-ground transmitters, as well as deal with the fact it is not currently interpreting my wifi-iface sections, is I modified the defaults inside the program:
```
local Device = {}
Device.__index = Device
Device.conf_options = {
-- MODIFICATION
-- signal_connect = DeviceOpt("signal_connect", tonumber, -128),
-- signal_stay = DeviceOpt("signal_stay", tonumber, -128),
-- snr_connect = DeviceOpt("signal_snr_connect", tonumber, 0),
-- snr_stay = DeviceOpt("signal_snr_stay", tonumber, 0),
-- poll_time = DeviceOpt("signal_poll_time", tonumber, 3),
-- strikes = DeviceOpt("signal_strikes", tonumber, 3),
   signal_connect = DeviceOpt("signal_connect", tonumber, 0),
   signal_stay = DeviceOpt("signal_stay", tonumber, 0),
   snr_connect = DeviceOpt("signal_snr_connect", tonumber, 30),
   snr_stay = DeviceOpt("signal_snr_stay", tonumber, 20),
   poll_time = DeviceOpt("signal_poll_time", tonumber, 3),
   strikes = DeviceOpt("signal_strikes", tonumber, 5),
   drop_reason = DeviceOpt("signal_drop_reason", tonumber, 3),
   whitelist = DeviceOpt("signal_whitelist", prefix_list_matcher, nil),
   blacklist = DeviceOpt("signal_blacklist", prefix_list_matcher, nil),
}
```

That way, I worked around the wifi-iface incompatibility, and at the same time do not need to reconfigure them. Create them with Luci as normal, put the two files in /etc/init.d and /usr/bin, and I am all done.

Thanks

**Comment by cybermaus** [comment]
PS: I am running an old version of OpenWRT, on purpose. 15.05.1 instead if 18.06,1

But I think neither version by default has a name in the wifi-iface section. Though it certainty is allowed for both. Maybe the generation of it was only on 17 LEDE? I never did do much with that version, the whole split and merge sort of passed me by, my devices were stable and untouched at that time.

I am rebuilding the entire Campground network, with VLAN to split Guests, Private and Devices (IoT). But it seems to work OK in 15.05.1, and 18.06.1 uses more of my somewhat limited RAM. So even though I experimented with 18, I see no reason to upgrade

**Comment by cybermaus** [comment]
Just for your information, I made a few more personal modifications. Not sure if you want to consider them (never programmed lua before, so it may be a bit crudely done):

1) Changed representation of MAC to lowercase. This so it matches that of hostapd in syslog, so you can do stuff like: `logread | grep 54:ef:5c` and get to see messages from both hostapd and wifi-disconnect in one screen.
```
function STA.new(addr)
   local self = setmetatable({}, STA)
-- MODIFICATION added :lower() to match hostapd in syslog
   self.addr = addr:lower()
   self.subject = addr:gsub(":", ""):upper()
```
2) Changed these two messages from dbg() to inf() so I get just enough info in syslog with only one -v
```
   for _, addr in ipairs(to_remove) do
-- MODIFICATION dbg() to inf()
      inf("%s: forget %s", self.ifname, addr:lower())
      self.stas[addr] = nil
```
```
while #devices == 0 do
   devices = get_wifi_devices()
-- MODIFICATION dbg() to inf()
   inf("found %d enabled WiFi devices", #devices)
end
```
3) Added one -v to the startup
```
start_service() {
        procd_open_instance
# MODIFICATION added -v option
        procd_set_param command "$PROG" -v
        procd_set_param file /etc/config/wireless
```
4) And of course the already mentioned defaults, so I do not need to change each interface on each device I have, as well as work around the wifi-iface label incompatibility.
```
Device.conf_options = {
-- MODIFICATION
-- signal_connect = DeviceOpt("signal_connect", tonumber, -128),
-- signal_stay = DeviceOpt("signal_stay", tonumber, -128),
-- snr_connect = DeviceOpt("signal_snr_connect", tonumber, 0),
-- snr_stay = DeviceOpt("signal_snr_stay", tonumber, 0),
-- poll_time = DeviceOpt("signal_poll_time", tonumber, 3),
-- strikes = DeviceOpt("signal_strikes", tonumber, 3),
   signal_connect = DeviceOpt("signal_connect", tonumber, 0),
   signal_stay = DeviceOpt("signal_stay", tonumber, 0),
   snr_connect = DeviceOpt("signal_snr_connect", tonumber, 30),
   snr_stay = DeviceOpt("signal_snr_stay", tonumber, 20),
   poll_time = DeviceOpt("signal_poll_time", tonumber, 3),
   strikes = DeviceOpt("signal_strikes", tonumber, 5),
```

Thanks for the great tool!

**Comment by barbieri** [comment]
is there anything pending? Or should we close this?
