### ISSUE TITLE
how reliable is curl-websocket? 

### ISSUE THREAD

**Issue by mlite** [barbieri/barbieri-playground#9]
I like your simple implementation of websocket client based on libcurl, and want to use it in one of my projects.  However, I was wondering how reliable it is?    The project is a bot that will connect to a websocket service forever.   Any advice will be highly appreciated.

**Comment by barbieri** [comment]
"my code, no bugs" 😆 

seriously, I wrote that code and tested for a while, but nothing I put too much effort or checks. Seems that other people do use it in their products/production, but I'm not sure if they found issues and if they fixed them.

I think it's okay, a very thin layer on top of curl... but I'd recommend you to run using valgrind and compile with some sanitizers to guarantee memory is not leaking, not doing any off-by-one access and so on.

If you do find, please send me a simple test case and I'll try to fix.

**Comment by mlite** [comment]
> "my code, no bugs" 

Love this confidence. 

> seriously, I wrote that code and tested for a while, but nothing I put too much effort or checks. Seems that other people do use it in their products/production, but I'm not sure if they found issues and if they fixed them.
> 
> I think it's okay, a very thin layer on top of curl... but I'd recommend you to run using valgrind and compile with some sanitizers to guarantee memory is not leaking, not doing any off-by-one access and so on.
> 
> If you do find, please send me a simple test case and I'll try to fix.

Thanks for the response. If we find any memory errors, I will file issues.

**Comment by barbieri** [comment]
btw, "my code, no bugs" was a joke :)
